[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyaging"
authors = [{name = "Lucas Paulo de Lima Camillo", email = "lucas_camillo@alumni.brown.edu"}]
dynamic = ["version", "description"]
