name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.3
  - pip:
      - sphinx>=7.2.6
      - sphinx-rtd-theme>=1.3.0
      - sphinx-autodoc-typehints>=1.12.0
      - ipykernel>=5.1.0
      - nbsphinx>=0.8.11
      - pygments>=2.6.1
      - pytest>=7.2.0
      - nbmake>=1.4.6
      - nbsphinx-link
      - scikit-learn>=1.3.2
      - pandas>=2.1.3
      - torch>=2.1.1
      - numpy>=1.26.2
      - pyBigWig>=0.3.22
      - anndata>=0.10.3

