name: build

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download success flag
      uses: actions/download-artifact@v2
      with:
        name: test-success-flag

    - name: Check if test was successful
      run: |
        if [ ! -f path-to-success-flag-file ]; then
          echo "Test workflow failed. Exiting build process."
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build Package
      run: |
        python -m pip install poetry
        poetry build
