name: Test, build, publish, and release

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'tutorials/**'
      - 'pyaging/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Automated Version Bumping
      id: autobump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch # or minor, major 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run Notebooks
      run: |
        poetry run pytest --nbmake tutorials/

    - name: Build Package
      run: |
        poetry build

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Create GitHub Release
      if: steps.autobump.outputs.new_tag != ''
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: ${{ steps.autobump.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
