name: publish

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get latest tag
      run: |
        LATEST_TAG=$(git rev-list --tags --max-count=1)
        if [ -z "$LATEST_TAG" ]; then
         echo "No tags found in the repository."
          exit 1 # or handle this situation as you see fit
        else
          LATEST_TAG_NAME=$(git describe --tags $LATEST_TAG)
          echo "LATEST_TAG=$LATEST_TAG_NAME" >> $GITHUB_ENV
        fi

    - name: Create Release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.LATEST_TAG }}
        release_name: Release ${{ env.LATEST_TAG }}
        body: Release of version ${{ env.LATEST_TAG }}

  publish-to-pypi:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/